resolver: lts-15.13
packages:
- .
- ..\DatabaseHelpers
- ..\CrudGenerator
- ..\InitializeDatabase
extra-deps:
- direct-sqlite-2.3.26
- Cabal-3.2.0.0
- http-server-1.0.6
- mime-0.4.0.2
- network-2.8.0.1
- HTTP-4000.3.14
- time-1.9.3
- shakespeare-2.0.24
- blaze-html-0.9.1.2
- http-types-0.12.3
- blaze-builder-0.4.1.0
- url-2.1.3
